# Generated by Django 2.2.5 on 2019-09-18 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190918_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='random_string',
        ),
    ]
