# Generated by Django 2.2.5 on 2019-09-18 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('match_date', models.DateTimeField(blank=True, null=True)),
                ('match_result', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.IntegerField(default=0)),
                ('wicket', models.IntegerField(default=0)),
                ('over', models.FloatField(default=0.0)),
                ('status', models.CharField(blank=True, choices=[('won', 'Won'), ('loss', 'Loss'), ('draw', 'Draw')], max_length=10)),
                ('point', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_card_match', to='match.Match')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('logo_uri', models.ImageField(upload_to='team_logo/')),
                ('club_state', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='ScoreCardPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.IntegerField(default=0)),
                ('wicket', models.IntegerField(default=0)),
                ('over', models.FloatField(default=0.0)),
                ('fifty', models.IntegerField(default=0)),
                ('hundred', models.IntegerField(default=0)),
                ('meadan_over', models.FloatField(default=0)),
                ('fours', models.IntegerField(default=0)),
                ('sixs', models.IntegerField(default=0)),
                ('man_of_match', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('out', 'Out'), ('notout', 'Not Out'), ('notplayed', 'Not Played')], max_length=10)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_score', to=settings.AUTH_USER_MODEL)),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_player', to='match.ScoreCard')),
            ],
        ),
        migrations.AddField(
            model_name='scorecard',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_card_team', to='match.Team'),
        ),
        migrations.CreateModel(
            name='MatchPlayerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_player', to='match.Match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_player', to=settings.AUTH_USER_MODEL)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_team', to='match.Team')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='match.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='match.Team'),
        ),
    ]
