# Generated by Django 2.2.5 on 2019-09-18 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_auto_20190918_0844'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='match',
            table='match',
        ),
        migrations.AlterModelTable(
            name='matchplayerdetails',
            table='match_player_detail',
        ),
        migrations.AlterModelTable(
            name='scorecard',
            table='score_card',
        ),
        migrations.AlterModelTable(
            name='scorecardplayer',
            table='score_card_player',
        ),
    ]
